name: Patikrinam
on: [push]


jobs:
 build:
  name: Lintinam
  runs-on: node
  steps:
  - name: Irasome tslint ir eslint
  run: npm install --save-dev eslint globals @eslint/js tslint
  - name: Pradedam testus
  run: npm run test
  run: npm run lint_es
  run: npm run lint_ts
  
  
