---
name: Patikrinam
on:
  workflow_dispatch:
jobs:
 pirma_dalis:
  runs-on: ubuntu-latest
  name: Irasome tslint ir eslint  
  run: npm install --save-dev eslint globals @eslint/js tslint
#   - name: Pradedam testus
#     run: npm run test && npm run lint_es && npm run lint_ts
