---
name: Patikrinam
on: workflow_dispatc
jobs:
  build:
    name: Lintinam
    runs-on: node
    steps:
      - name: Irasome tslint ir eslint
        run: npm install --save-dev eslint globals @eslint/js tslint
      - name: Pradedam testus
        run: npm run test && workflow_dispatc && npm run lint_ts
