name: Patikrinam
on:
 workflow_dispatch:

jobs:
 pirma_dalis:
  name: Praruosiam ir lintinam
  runs-on: ubuntu-latest  
  steps:  
   - uses: actions/checkout@v4
     with:
      sparse-checkout: |
       uzduotis_16_05/CodeAcademyTask
   - name: Instaliuojam dependencys
     run: |
      cd uzduotis_16_05/CodeAcademyTask
      npm install --save-dev eslint globals @eslint/js tslint
   - name: Bandom testus
     uses: actions/setup-node@v4
      run: |
       cd uzduotis_16_05/CodeAcademyTask
       npm ci
       npm run build --if-present
       npm test
#      cd uzduotis_16_05/CodeAcademyTask
#      npm run test
