name: Patikrinam
on:
 workflow_dispatch:

jobs:
 pirma_dalis:
  name: Praruosiam ir lintinam
  runs-on: ubuntu-latest  
  steps:  
   - uses: actions/checkout@v4
     with:
      sparse-checkout: |
       uzduotis_16_05/CodeAcademyTask
     working-directory: uzduotis_16_05/CodeAcademyTask
   - name: Instaliuojam dependencys
     run: |
      npm install --save-dev eslint globals @eslint/js tslint
   - name: Bandom testus
     run: |
      npm run test
