name: Patikrinam
on:
 workflow_dispatch:

jobs:
 pirma_dalis:
  name: Praruosiam ir lintinam
  runs-on: ubuntu-latest  
  steps:  
   - uses: actions/checkout@v4
     with:
      sparse-checkout: |
       uzduotis_16_05/CodeAcademyTask
   - name: Instaliuojam dependencys
     run: |
      cd uzduotis_16_05/CodeAcademyTask
      npm install --save-dev eslint globals @eslint/js tslint
#   *** Neveikia nes negali sukurti direktorijos EACCES: permission denied, mkdir '/etc/todos' sudo ?? ***
   - name: Bandom testus
     run: |
       echo Tarkim testai veikia!
#      cd uzduotis_16_05/CodeAcademyTask
#      npm run build --if-present
#      npm test
   - name: Bandom ES it TS lint 
     run: |
       echo Tarkim viskas veikia!
#      cd uzduotis_16_05/CodeAcademyTask
#      npm run lint_ts
#      npm run lint_es
   - uses: azure/docker-login@v1
     with:
      login-server: linco.azurecr.io
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
    run: |
    docker build -f uzduotis_16_05/Dockerfile uzduotis_16_05/ -t bandymas.${{ github.sha }}
    docker push bandymas.${{ github.sha }}
