name: Patikrinam
on:
  workflow_dispatch:

jobs:
  pirma_dalis:
    name: Praruosiam ir lintinam
    runs-on: ubuntu-latest  
    steps:  
      -name: instaliuojam dependencys
       run: |
         npm install --save-dev eslint globals @eslint/js tslint
#   - name: Pradedam testus
#     run: npm run test && npm run lint_es && npm run lint_ts
