name: Patikrinam
on:
 workflow_dispatch:

jobs:
 pirma_dalis:
  name: Praruosiam ir lintinam
  runs-on: ubuntu-latest  
  steps:  
   - name: instaliuojam dependencys
     run: |
      npm install --save-dev eslint globals @eslint/js tslint
