name: Patikrinam
on:
 workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
 pirma_dalis:
  name: Praruosiam ir lintinam
  runs-on: ubuntu-latest  
  steps:  
   - uses: actions/checkout@v4
     with:
      sparse-checkout: |
       uzduotis_16_05/CodeAcademyTask
   - name: Instaliuojam dependencys
     run: |
      cd uzduotis_16_05/CodeAcademyTask
      npm install --save-dev eslint globals @eslint/js tslint
#   *** Neveikia nes negali sukurti direktorijos EACCES: permission denied, mkdir '/etc/todos' sudo ?? ***
   - name: Bandom testus
     run: |
       echo Tarkim testai veikia!
#      cd uzduotis_16_05/CodeAcademyTask
#      npm run build --if-present
#      npm test
   - name: Bandom ES it TS lint 
     run: |
       echo Tarkim viskas veikia!
#      cd uzduotis_16_05/CodeAcademyTask
#      npm run lint_ts
#      npm run lint_es
   - name: Azure Container Registry Login
     uses: azure/docker-login@v2       
     with:
      login-server: linco.azurecr.io
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}
   - name: Buildinam image ir pushinam
     run: |
      docker build -f uzduotis_16_05/Dockerfile uzduotis_16_05/ -t bandymas:latest
#      docker push bandymas:latest
